Session stateless
coforma-acme/acme-tech-challenge pull request #83
Opened 2022-08-09 20:37 UTC by sareenb

1. disabled userid password login mechanism
2. made application stateless . to make role enforcing obvious
3. added swagger config to for authorization
4. removed duplicate data.sql in test resources

2022-08-09 20:47 UTC, caoabunga requested changes

2022-08-09 20:47 UTC, caoabunga commented on acme/src/test/resources/application-test.properties
> +spring.jpa.hibernate.ddl-auto=create
Did you mean this?

2022-08-09 21:02 UTC, gmrabian commented
I see you removed `data.sql` from the test folder. Are the tests still passing? They failed for me when I tried that.

2022-08-10 01:42 UTC, sareenb commented on acme/src/test/resources/application-test.properties
> +spring.jpa.hibernate.ddl-auto=create
Yes . This is for test data base only.

2022-08-10 14:20 UTC, caoabunga approved these changes

2022-08-10 14:20 UTC, merged